### ISSUE TITLE
Allow local traffic on some interfaces

### ISSUE THREAD

**Issue by drbild** [xaptum/enftun#31]
Issue #29 will block non-tunnel traffic from all interfaces, including local traffic.  This is the default behavior that we desire.

However, in some situations local traffic should be allowed. For example, in our bacnet setup, there are two physical interfaces, `wlan0` connected to the internet and `eth0` connected to the local BACnet/IP installation.  Local traffic should be blocked on `wlan0`, but should be allowed on the "trusted" `eth0` interface.

Here is my suggested approach, for now.

Generally local traffic should only be allowed on trusted networks. These will be local, on-prem networks that are not connected to the internet themselves (like the BACnet/IP network in our demo).

Each interface on a host will either be connected to a trusted network (`eth0` in our bacnet demo) or an untrusted network (`wlan0` in our bacnet demo).

So, we can allow local traffic for any interfaces that are trusted.  This can be accomplished by accepting a list of trusted interfaces in the `enftun` config file and configuring a `suppress_ifgroup` rule for them.

### Tasks

- [x] Add a `trusted_interfaces` parameter to the config that takes a list of interface names.
- [x] In `enftun-setup`, create an [interface group](https://baturin.org/docs/iproute2/#Link%20group%20management containing these interfaces.
- [x] In `enftun-setup`, create a `suppress_ifgroup` rule for those interfaces, similar to the the `suppress_prefixlength` rule prior to the fix of #29.

**Comment by drbild** [comment]
Closed by #36
